name       : qspeakers
version    : 1.6.1
release    : 1
source     :
    - http://brouits.free.fr/qspeakers/qspeakers-1.6.1.tar.gz : 62b829f7344e091e0106f2ad76908dcda6762fc279699d6b85d8a867dbe4fd33
license    : GPL-3.0-or-later
component  : office.scientific
homepage   : http://brouits.free.fr/qspeakers/
summary    : Loudspeaker enclosure design software
description: |
    QSpeakers is a simple graphical program that simulates common acoustical enclosures behaviour based on the loudspeaker driver's Thiele / Small parameters and the chosen enclosure type.
builddeps  :
    - pkgconfig(Qt5Charts)
    - pkgconfig(Qt5Xml)
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
