name       : qspeakers
version    : 1.6.2
release    : 2
source     :
    - http://brouits.free.fr/qspeakers/qspeakers-1.6.2.tar.gz : c4a3fc5ae53914825ed3a74e243594f5569e988173437598c2cc28a211188654
license    : GPL-3.0-or-later
component  : office.scientific
homepage   : http://brouits.free.fr/qspeakers/
summary    : Loudspeaker enclosure design software
description: |
    QSpeakers is a simple graphical program that simulates common acoustical enclosures behaviour based on the loudspeaker driver's Thiele / Small parameters and the chosen enclosure type.
builddeps  :
    - pkgconfig(Qt5Charts)
    - pkgconfig(Qt5Xml)
    - pkgconfig(Qt5UiTools)
setup      : |
    %patch -p1 < $pkgfiles/fix_metainfo_xml.patch
    %qmake PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
